/* vertices */
CREATE CLASS Uzivatel EXTENDS V;
CREATE CLASS Soubor EXTENDS V;
CREATE CLASS Faktura EXTENDS V;
CREATE CLASS Uctenka EXTENDS V;
CREATE CLASS CarovyKod EXTENDS V;
CREATE CLASS Objednavka EXTENDS V;
CREATE CLASS FormatovanyText EXTENDS V;
CREATE CLASS Akce EXTENDS V;
CREATE CLASS PraceNaAkci EXTENDS V;
CREATE CLASS PridelAkci EXTENDS V;
CREATE CLASS ZpusobUhrady EXTENDS V;
CREATE CLASS Rozpocet EXTENDS V;
CREATE CLASS PolozkaRozpoctu EXTENDS V;
CREATE CLASS Organ EXTENDS V;

/* edges */
CREATE CLASS Vlastnik EXTENDS E;
CREATE CLASS Schvaleno EXTENDS E;

/* vertex properties */
CREATE PROPERTY Uzivatel.id INTEGER (MANDATORY TRUE, NOTNULL TRUE);
CREATE PROPERTY Uzivatel.login STRING (MANDATORY TRUE, NOTNULL TRUE);
CREATE PROPERTY Uzivatel.jmeno STRING (MANDATORY TRUE);
CREATE PROPERTY Uzivatel.prijmeni STRING (MANDATORY TRUE);
CREATE PROPERTY Uzivatel.prezdivka STRING (MANDATORY TRUE);
CREATE PROPERTY Uzivatel.email STRING (MANDATORY TRUE);
CREATE PROPERTY Uzivatel.variabilni_symbol INTEGER;
CREATE INDEX Uzivatel.id UNIQUE;
CREATE INDEX Uzivatel.login UNIQUE;
CREATE INDEX Uzivatel.variabilni_symbol UNIQUE;
/* CREATE INDEX Uzivatel.email UNIQUE; */

CREATE PROPERTY Soubor.uuid STRING (MANDATORY TRUE, NOTNULL TRUE, DEFAULT "uuid()", READONLY TRUE);
CREATE PROPERTY Soubor.mediaType STRING (MANDATORY TRUE, NOTNULL FALSE);
CREATE PROPERTY Soubor.name STRING (MANDATORY TRUE, NOTNULL FALSE);
CREATE PROPERTY Soubor.popis STRING (MANDATORY FALSE);
CREATE PROPERTY Soubor.netadmin STRING (MANDATORY FALSE);
CREATE INDEX Soubor.uuid UNIQUE;

CREATE PROPERTY CarovyKod.hodnota STRING (MANDATORY TRUE);
CREATE INDEX CarovyKod.hodnota UNIQUE;

CREATE PROPERTY Akce.nazev STRING (MANDATORY TRUE);
CREATE PROPERTY Akce.popis EMBEDDED FormatovanyText (MANDATORY TRUE);
CREATE PROPERTY Akce.schvalena DATE (MANDATORY TRUE);
CREATE PROPERTY Akce.odkaz STRING (MANDATORY TRUE);
CREATE PROPERTY Akce.netadmin INTEGER (MANDATORY FALSE);

CREATE PROPERTY PridelAkci.akce LINK Akce (MANDATORY TRUE, NOTNULL TRUE);
CREATE PROPERTY PridelAkci.popis EMBEDDED FormatovanyText (MANDATORY TRUE);
CREATE PROPERTY PridelAkci.schvalen DATE (MANDATORY TRUE);
CREATE PROPERTY PridelAkci.odkaz STRING (MANDATORY TRUE);

CREATE PROPERTY PraceNaAkci.akce LINK Akce (MANDATORY TRUE, NOTNULL TRUE);
CREATE PROPERTY PraceNaAkci.popis EMBEDDED FormatovanyText (MANDATORY TRUE);
CREATE PROPERTY PraceNaAkci.uzivatel LINK Uzivatel (MANDATORY TRUE, NOTNULL TRUE);
CREATE PROPERTY PraceNaAkci.castka DECIMAL (MANDATORY TRUE, NOTNULL TRUE);
CREATE PROPERTY PraceNaAkci.datum DATE (MANDATORY TRUE);

CREATE PROPERTY FormatovanyText.text STRING (MANDATORY TRUE);
CREATE PROPERTY FormatovanyText.format STRING (MANDATORY TRUE);

CREATE PROPERTY Objednavka.popis STRING (MANDATORY TRUE);
CREATE PROPERTY Objednavka.castka DECIMAL (MANDATORY TRUE);
CREATE PROPERTY Objednavka.datumObjednani DATE (MANDATORY TRUE);
CREATE PROPERTY Objednavka.datumSplatnosti DATE;
CREATE PROPERTY Objednavka.zpusobUhrady LINK ZpusobUhrady (MANDATORY TRUE);
CREATE PROPERTY Objednavka.uhrazenoKym LINK Uzivatel;
CREATE PROPERTY Objednavka.dodavatel STRING;
CREATE PROPERTY Objednavka.ico STRING;
CREATE PROPERTY Objednavka.cisloUctu STRING;
CREATE PROPERTY Objednavka.variabilniSymbol STRING;
CREATE PROPERTY Objednavka.poznamka EMBEDDED FormatovanyText;

CREATE PROPERTY Faktura.uuid STRING (MANDATORY TRUE, NOTNULL TRUE, DEFAULT "uuid()", READONLY TRUE);
CREATE PROPERTY Faktura.flexibee_id LONG (MANDATORY TRUE, NOTNULL FALSE);
CREATE INDEX Faktura.uuid UNIQUE;
CREATE INDEX Faktura.flexibee_id NOTUNIQUE;

CREATE PROPERTY Uctenka.uuid STRING (MANDATORY TRUE, NOTNULL TRUE, DEFAULT "uuid()", READONLY TRUE);
CREATE INDEX Uctenka.uuid UNIQUE;

CREATE PROPERTY ZpusobUhrady.nazev STRING (MANDATORY TRUE, NOTNULL TRUE);
CREATE PROPERTY ZpusobUhrady.kod STRING (MANDATORY TRUE, NOTNULL TRUE);
CREATE INDEX ZpusobUhrady.kod UNIQUE;

CREATE PROPERTY Organ.nazev STRING (MANDATORY TRUE, NOTNULL TRUE);
CREATE PROPERTY Organ.kod STRING (MANDATORY TRUE, NOTNULL TRUE);
CREATE PROPERTY Organ.nadrizenyOrgan LINK Organ (MANDATORY FALSE);
CREATE INDEX Organ.nazev UNIQUE;
CREATE INDEX Organ.kod UNIQUE;

CREATE PROPERTY Rozpocet.rok INTEGER (MANDATORY TRUE, NOTNULL TRUE);
CREATE PROPERTY Rozpocet.polozky LINKLIST PolozkaRozpoctu (MANDATORY TRUE, NOTNULL TRUE);

CREATE PROPERTY PolozkaRozpoctu.nazev STRING (MANDATORY TRUE, NOTNULL TRUE);
CREATE PROPERTY PolozkaRozpoctu.castka DECIMAL (MANDATORY TRUE, NOTNULL TRUE);
CREATE PROPERTY PolozkaRozpoctu.organ LINK Organ (MANDATORY TRUE, NOTNULL TRUE);
CREATE PROPERTY PolozkaRozpoctu.podkapitoly LINKLIST PolozkaRozpoctu (MANDATORY FALSE);

/* edge properties */
CREATE PROPERTY Vlastnik.out LINK Uzivatel (MANDATORY TRUE, NOTNULL TRUE);

CREATE PROPERTY Schvaleno.out LINK Uzivatel (MANDATORY TRUE, NOTNULL TRUE);
CREATE PROPERTY Schvaleno.datum DATETIME (MANDATORY TRUE, NOTNULL TRUE);
