//vertices
CREATE CLASS Faktura EXTENDS V;
CREATE CLASS Uctenka EXTENDS V;

//vertex properties
CREATE PROPERTY Faktura.uuid STRING (MANDATORY TRUE, NOTNULL TRUE, DEFAULT "uuid()", READONLY TRUE);
CREATE PROPERTY Faktura.flexibee_id LONG (MANDATORY TRUE, NOTNULL FALSE);
CREATE INDEX Faktura.uuid UNIQUE;
CREATE INDEX Faktura.flexibee_id NOTUNIQUE;

CREATE PROPERTY Uctenka.uuid STRING (MANDATORY TRUE, NOTNULL TRUE, DEFAULT "uuid()", READONLY TRUE);
CREATE INDEX Uctenka.uuid UNIQUE;