micronaut:
  application:
    default-charset: UTF-8
    name: czela.evidence.backend
  http:
    services:
      flexibee:
        url: https://flexibee-web.czela.net
        path: /c/czela_test/
  server:
    cors:
      enabled: true
    port: 8081
  security:
    enabled: true
    endpoints:
      login:
        enabled: false
      logout:
        enabled: false
    token:
      jwt:
        enabled: true
        bearer:
          enabled: true
        signatures:
          jwks:
            czela:
              keyType: EC
              url: https://www.czela.net/.well-known/jwks.json
datasources:
#  netadmin:
#    url: jdbc:mysql://kazbunda.czela.net:3306/netadmin?characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
#    driverClassName: com.mysql.cj.jdbc.Driver
jackson:
  serialization:
    writeDatesAsTimestamps: false