micronaut:
  security:
    enabled: true
    endpoints:
      login:
        enabled: true
      logout:
        enabled: true
    token:
      jwt:
        enabled: true
        bearer:
          enabled: true
        signatures:
          jwks:
            czela:
              keyType: EC
              url: https://www.czela.net/.well-known/jwks.json
#          secret:
#            generator:
#              secret: pleaseChangeThisSecretForANewOne